from enum import Enum


class UserRole(str, Enum):
    STUDENT = "STUDENT"
    DEPARTMENT_STAFF = "DEPARTMENT_STAFF"
    ADMINISTRATOR = "ADMINISTRATOR"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class ComplaintPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComplaintStatus(str, Enum):
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"


class DepartmentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class NotificationPriority(str, Enum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class NotificationType(str, Enum):
    COMPLAINT_SUBMITTED = "COMPLAINT_SUBMITTED"
    COMPLAINT_ASSIGNED = "COMPLAINT_ASSIGNED"
    COMPLAINT_STATUS_UPDATED = "COMPLAINT_STATUS_UPDATED"
    COMPLAINT_PRIORITY_UPDATED = "COMPLAINT_PRIORITY_UPDATED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
    COMPLAINT_UPDATE_ADDED = "COMPLAINT_UPDATE_ADDED"
    CRITICAL_COMPLAINT = "CRITICAL_COMPLAINT"
    DEPARTMENT_ASSIGNMENT = "DEPARTMENT_ASSIGNMENT"
    ADMIN_ALERT = "ADMIN_ALERT"
    SYSTEM_UPDATE = "SYSTEM_UPDATE"
    ANNOUNCEMENT = "ANNOUNCEMENT"

