from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserStatusUpdate,
    UserRoleUpdate,
    UserResponse,
    UserListResponse,
)
from app.schemas.department import (
    DepartmentCreate,
    DepartmentUpdate,
    DepartmentStatusUpdate,
    DepartmentResponse,
    DepartmentListResponse,
)
from app.schemas.complaint import (
    ComplaintCreate,
    ComplaintUpdateRequest,
    ComplaintStatusUpdate,
    ComplaintPriorityUpdate,
    ComplaintDepartmentUpdate,
    ComplaintAddUpdate,
    ComplaintResolve,
    ComplaintResponse,
    ComplaintListResponse,
    ComplaintTimelineResponse,
    AttachmentResponse,
    ComplaintUpdateResponse,
)
from app.schemas.notification import (
    NotificationResponse,
    NotificationListResponse,
    UnreadCountResponse,
)
from app.schemas.analytics import (
    AnalyticsOverview,
    TrendDataPoint,
    CategoryDataPoint,
    PriorityDataPoint,
    StatusDataPoint,
    DepartmentWorkloadPoint,
    ResolutionTimePoint,
)
from app.schemas.dashboard import (
    StudentDashboardResponse,
    AdminDashboardResponse,
    DepartmentDashboardResponse,
)

__all__ = [
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserCreate",
    "UserUpdate",
    "UserStatusUpdate",
    "UserRoleUpdate",
    "UserResponse",
    "UserListResponse",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentStatusUpdate",
    "DepartmentResponse",
    "DepartmentListResponse",
    "ComplaintCreate",
    "ComplaintUpdateRequest",
    "ComplaintStatusUpdate",
    "ComplaintPriorityUpdate",
    "ComplaintDepartmentUpdate",
    "ComplaintAddUpdate",
    "ComplaintResolve",
    "ComplaintResponse",
    "ComplaintListResponse",
    "ComplaintTimelineResponse",
    "AttachmentResponse",
    "ComplaintUpdateResponse",
    "NotificationResponse",
    "NotificationListResponse",
    "UnreadCountResponse",
    "AnalyticsOverview",
    "TrendDataPoint",
    "CategoryDataPoint",
    "PriorityDataPoint",
    "StatusDataPoint",
    "DepartmentWorkloadPoint",
    "ResolutionTimePoint",
    "StudentDashboardResponse",
    "AdminDashboardResponse",
    "DepartmentDashboardResponse",
]
